name: fitness
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  charts_flutter: ^0.12.0
  http: ^1.2.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - gym.png

flutter_icons:
  android: true
  ios: true
  image_path: "gym.png"
